### ISSUE TITLE
URLs as Text as well as in Screenshots

### ISSUE THREAD

**Issue by WardsParadox** [smashism/awesome-macadmin-tools#17]
Firstly,
Thank you for putting a lot of the tools the mac admin community uses in a clear concise list.
Would it be possible to add URLs to the bottom of the screenshots or at the bottom of the descriptions in addition to the URLs wrapped around the images? It took me way longer than I would like to admit to finding the links built into the images. I can fork and add them if you would like.

**Comment by smashism** [comment]
Let me muse on the best way to format that and get back to you… I think this is a fantastic suggestion that will improve the experience of getting to the tools themselves, thank you!

**Comment by smashism** [comment]
Done!
